CREATE TABLE `series`
(
    `id`            bigint      NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
    `series_id`     varchar(64) NOT NULL COMMENT 'Series ID (ID returned by API)',
    `ticker`        varchar(128)   DEFAULT NULL COMMENT 'Series Ticker',
    `slug`          varchar(255)   DEFAULT NULL COMMENT 'URL Slug',
    `title`         varchar(512)   DEFAULT NULL COMMENT 'Series Title',
    `series_type`   varchar(32)    DEFAULT NULL COMMENT 'Series Type',
    `recurrence`    varchar(32)    DEFAULT NULL COMMENT 'Recurrence Type (daily/weekly, etc.)',
    `image`         varchar(1024)  DEFAULT NULL COMMENT 'Image URL',
    `icon`          varchar(1024)  DEFAULT NULL COMMENT 'Icon URL',
    `active`        tinyint(1) DEFAULT 1 COMMENT 'Is Active',
    `closed`        tinyint(1) DEFAULT 0 COMMENT 'Is Closed',
    `archived`      tinyint(1) DEFAULT 0 COMMENT 'Is Archived',
    `volume`        decimal(24, 6) DEFAULT NULL COMMENT 'Total Volume',
    `volume_24hr`   decimal(24, 6) DEFAULT NULL COMMENT '24 Hour Volume',
    `liquidity`     decimal(24, 6) DEFAULT NULL COMMENT 'Liquidity',
    `comment_count` int            DEFAULT 0 COMMENT 'Comment Count',
    `created_at`    datetime       DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation Time',
    `updated_at`    datetime       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update Time',
    `deleted`       tinyint(1) DEFAULT 0 COMMENT 'Logical Delete Flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_series_id` (`series_id`),
    KEY             `idx_recurrence` (`recurrence`),
    KEY             `idx_active_closed` (`active`, `closed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Event Series Table';


CREATE TABLE `event`
(
    `id`                 bigint      NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
    `event_id`           varchar(64) NOT NULL COMMENT 'Event ID (ID returned by API)',
    `series_id`          varchar(64)    DEFAULT NULL COMMENT 'Associated Series ID',
    `ticker`             varchar(128)   DEFAULT NULL COMMENT 'Event Ticker',
    `slug`               varchar(255)   DEFAULT NULL COMMENT 'URL Slug',
    `title`              varchar(512)   DEFAULT NULL COMMENT 'Event Title',
    `description`        text COMMENT 'Event Description',
    `resolution_source`  varchar(1024)  DEFAULT NULL COMMENT 'Resolution Source URL',
    `image`              varchar(1024)  DEFAULT NULL COMMENT 'Image URL',
    `icon`               varchar(1024)  DEFAULT NULL COMMENT 'Icon URL',
    `active`             tinyint(1) DEFAULT 1 COMMENT 'Is Active',
    `closed`             tinyint(1) DEFAULT 0 COMMENT 'Is Closed',
    `archived`           tinyint(1) DEFAULT 0 COMMENT 'Is Archived',
    `isNew`                tinyint(1) DEFAULT 0 COMMENT 'Is New Event',
    `featured`           tinyint(1) DEFAULT 0 COMMENT 'Is Featured',
    `restricted`         tinyint(1) DEFAULT 0 COMMENT 'Is Restricted',
    `liquidity`          decimal(24, 6) DEFAULT NULL COMMENT 'Liquidity',
    `volume`             decimal(24, 6) DEFAULT NULL COMMENT 'Volume',
    `open_interest`      decimal(24, 6) DEFAULT NULL COMMENT 'Open Interest',
    `competitive`        decimal(10, 6) DEFAULT NULL COMMENT 'Competitiveness',
    `volume_24hr`        decimal(24, 6) DEFAULT NULL COMMENT '24 Hour Volume',
    `volume_1wk`         decimal(24, 6) DEFAULT NULL COMMENT '1 Week Volume',
    `volume_1mo`         decimal(24, 6) DEFAULT NULL COMMENT '1 Month Volume',
    `volume_1yr`         decimal(24, 6) DEFAULT NULL COMMENT '1 Year Volume',
    `enable_order_book`  tinyint(1) DEFAULT 0 COMMENT 'Is Order Book Enabled',
    `liquidity_clob`     decimal(24, 6) DEFAULT NULL COMMENT 'CLOB Liquidity',
    `neg_risk`           tinyint(1) DEFAULT 0 COMMENT 'Negative Risk Flag',
    `neg_risk_market_id` varchar(128)   DEFAULT NULL COMMENT 'Negative Risk Market ID',
    `comment_count`      int            DEFAULT 0 COMMENT 'Comment Count',
    `event_date`         date           DEFAULT NULL COMMENT 'Event Date',
    `start_date`         datetime       DEFAULT NULL COMMENT 'Start Time',
    `end_date`           datetime       DEFAULT NULL COMMENT 'End Time',
    `created_at`         datetime       DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation Time',
    `updated_at`         datetime       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update Time',
    `deleted`            tinyint(1) DEFAULT 0 COMMENT 'Logical Delete Flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_event_id` (`event_id`),
    KEY                  `idx_series_id` (`series_id`),
    KEY                  `idx_start_date` (`start_date`),
    KEY                  `idx_end_date` (`end_date`),
    KEY                  `idx_event_date` (`event_date`),
    KEY                  `idx_active_closed` (`active`, `closed`),
    KEY                  `idx_neg_risk_market_id` (`neg_risk_market_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Event Table';



CREATE TABLE `market`
(
    `id`                        bigint      NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
    `market_id`                 varchar(64) NOT NULL COMMENT 'Market ID (ID returned by API)',
    `event_id`                  varchar(64) NOT NULL COMMENT 'Associated Event ID',
    `condition_id`              varchar(128)   DEFAULT NULL COMMENT 'Condition ID',
    `question`                  varchar(1024)  DEFAULT NULL COMMENT 'Market Question',
    `slug`                      varchar(255)   DEFAULT NULL COMMENT 'URL Slug',
    `resolution_source`         varchar(1024)  DEFAULT NULL COMMENT 'Resolution Source URL',
    `image`                     varchar(1024)  DEFAULT NULL COMMENT 'Image URL',
    `icon`                      varchar(1024)  DEFAULT NULL COMMENT 'Icon URL',
    `description`               text COMMENT 'Market Description',
    `outcomes`                  json           DEFAULT NULL COMMENT 'Outcomes JSON Array',
    `outcome_prices`            json           DEFAULT NULL COMMENT 'Outcome Prices JSON Array',
    `clob_token_ids`            json           DEFAULT NULL COMMENT 'CLOB Token IDs JSON Array',
    `volume`                    decimal(24, 6) DEFAULT NULL COMMENT 'Volume',
    `liquidity`                 decimal(24, 6) DEFAULT NULL COMMENT 'Liquidity',
    `active`                    tinyint(1) DEFAULT 1 COMMENT 'Is Active',
    `closed`                    tinyint(1) DEFAULT 0 COMMENT 'Is Closed',
    `archived`                  tinyint(1) DEFAULT 0 COMMENT 'Is Archived',
    `isNew`                       tinyint(1) DEFAULT 0 COMMENT 'Is New Market',
    `featured`                  tinyint(1) DEFAULT 0 COMMENT 'Is Featured',
    `restricted`                tinyint(1) DEFAULT 0 COMMENT 'Is Restricted',
    `enable_order_book`         tinyint(1) DEFAULT 0 COMMENT 'Is Order Book Enabled',
    `order_price_min_tick_size` decimal(10, 4) DEFAULT NULL COMMENT 'Minimum Price Tick Size',
    `order_min_size`            decimal(10, 2) DEFAULT NULL COMMENT 'Minimum Order Size',
    `group_item_title`          varchar(128)   DEFAULT NULL COMMENT 'Group Item Title',
    `group_item_threshold`      varchar(32)    DEFAULT NULL COMMENT 'Group Item Threshold',
    `question_id`               varchar(128)   DEFAULT NULL COMMENT 'Question ID',
    `neg_risk`                  tinyint(1) DEFAULT 0 COMMENT 'Negative Risk Flag',
    `neg_risk_market_id`        varchar(128)   DEFAULT NULL COMMENT 'Negative Risk Market ID',
    `neg_risk_request_id`       varchar(128)   DEFAULT NULL COMMENT 'Negative Risk Request ID',
    `spread`                    decimal(10, 4) DEFAULT NULL COMMENT 'Spread',
    `best_bid`                  decimal(10, 4) DEFAULT NULL COMMENT 'Best Bid',
    `best_ask`                  decimal(10, 4) DEFAULT NULL COMMENT 'Best Ask',
    `last_trade_price`          decimal(10, 4) DEFAULT NULL COMMENT 'Last Trade Price',
    `one_hour_price_change`     decimal(10, 4) DEFAULT NULL COMMENT '1 Hour Price Change',
    `competitive`               decimal(10, 6) DEFAULT NULL COMMENT 'Competitiveness',
    `uma_bond`                  varchar(32)    DEFAULT NULL COMMENT 'UMA Bond',
    `uma_reward`                varchar(32)    DEFAULT NULL COMMENT 'UMA Reward',
    `fee_type`                  varchar(64)    DEFAULT NULL COMMENT 'Fee Type',
    `fee_schedule`              json           DEFAULT NULL COMMENT 'Fee Schedule JSON',
    `accepting_orders`          tinyint(1) DEFAULT 1 COMMENT 'Is Accepting Orders',
    `start_date`                datetime       DEFAULT NULL COMMENT 'Start Time',
    `end_date`                  datetime       DEFAULT NULL COMMENT 'End Time',
    `created_at`                datetime       DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation Time',
    `updated_at`                datetime       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update Time',
    `deleted`                   tinyint(1) DEFAULT 0 COMMENT 'Logical Delete Flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_market_id` (`market_id`),
    KEY                         `idx_event_id` (`event_id`),
    KEY                         `idx_condition_id` (`condition_id`),
    KEY                         `idx_neg_risk_market_id` (`neg_risk_market_id`),
    KEY                         `idx_question_id` (`question_id`),
    KEY                         `idx_active_closed` (`active`, `closed`),
    KEY                         `idx_start_date` (`start_date`),
    KEY                         `idx_end_date` (`end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Market Table';



CREATE TABLE `tag`
(
    `id`           bigint      NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
    `tag_id`       varchar(64) NOT NULL COMMENT 'Tag ID (ID returned by API)',
    `label`        varchar(128) DEFAULT NULL COMMENT 'Tag Label',
    `slug`         varchar(255) DEFAULT NULL COMMENT 'URL Slug',
    `force_show`   tinyint(1) DEFAULT 0 COMMENT 'Force Show Flag',
    `is_carousel`  tinyint(1) DEFAULT 0 COMMENT 'Is Carousel',
    `published_at` datetime     DEFAULT NULL COMMENT 'Publish Time',
    `created_at`   datetime     DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation Time',
    `updated_at`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update Time',
    `deleted`      tinyint(1) DEFAULT 0 COMMENT 'Logical Delete Flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tag_id` (`tag_id`),
    KEY            `idx_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tag Table';



CREATE TABLE `event_tag`
(
    `id`         bigint      NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
    `event_id`   varchar(64) NOT NULL COMMENT 'Event ID',
    `tag_id`     varchar(64) NOT NULL COMMENT 'Tag ID',
    `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation Time',
    `deleted`    tinyint(1) DEFAULT 0 COMMENT 'Logical Delete Flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_event_tag` (`event_id`, `tag_id`),
    KEY          `idx_event_id` (`event_id`),
    KEY          `idx_tag_id` (`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Event Tag Association Table';